---
title: "R Notebook"
output: html_notebook
---

## Context
As part of Reproducible Research course which is Mandatory course for 2nd year students of Data Science and Business Analytics, we are reproducing already existing project. 

Link to the project:
https://www.kaggle.com/code/alfiansyahachmad/walmart-sales-analysis-eda-and-econometrics

##All required libraries will be listed here

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(lubridate)
```

##First we read the dataset

```{r}
url<-"https://raw.githubusercontent.com/WojciechMisiura/rr_project/main/Walmart_Store_sales.csv" #as we already added our dataset to github, we will read data directly from github

data<-read_csv(url)

head(data)
```

```{r}
names(data)
```

```{r}
colnames(data)
```

```{r}
str(data)
```

```{r}
summary(data)
```

```{r}
colSums(is.na(data))
```

```{r}
any(duplicated(data))
```

```{r}
data$Date <- as.Date(data$Date, format = "%d-%m-%Y")

data$Weekly_Sales <- round(data$Weekly_Sales / 1000, 3)
data$CPI <- round(data$CPI, 2)

data2 <- data

data2 <- data2[order(data2$Date), ]

panel <- data2 %>%
  group_by(Store, Date) %>%
  summarise(
    Weekly_Sales = mean(Weekly_Sales),
    Holiday_Flag = mean(Holiday_Flag),
    Temperature = mean(Temperature),
    Fuel_Price = mean(Fuel_Price),
    CPI = mean(CPI),
    Unemployment = mean(Unemployment),
    .groups = "drop"
  )

panel$Month <- month(panel$Date)
panel$Year <- year(panel$Date)

head(panel)
```

```{r}
data_sub <- data[, !(names(data) %in% c('Month', 'Year', 'Store'))]

summary(data_sub)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```
